# Generated by Django 2.2.2 on 2019-08-06 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustible', models.CharField(choices=[('91', '91'), ('95', '95'), ('Gasoil', 'Gasoil')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(choices=[('Libertador', 'Libertador'), ('Campo Elias', 'Campo Elias'), ('Sucre', 'Sucre'), ('Santos Marquina', 'Santos Marquina')], default='Libertador', max_length=20)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(help_text='Sin espacio en blanco y letras en mayusculas', max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rebotado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebotados', to='gas_app.Combustible')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_app.Vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='combustible',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_app.Estacion'),
        ),
        migrations.CreateModel(
            name='Cola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('cargado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colas', to='gas_app.Combustible')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_app.Vehiculo')),
            ],
            options={
                'ordering': ('-last_modified_at',),
                'unique_together': {('vehiculo', 'combustible')},
            },
        ),
    ]
